# サイト設定
title: "IIMヒューマン・ソリューション株式会社"
description: >
  IIMヒューマン・ソリューション株式会社は、ITインフラを支えるスペシャリストの集団です。
baseurl: ""
url: "http://www.iimhs.co.jp"

# デフォルト設定
defaults:
  -
    scope:
      path: "cases"
      type: "posts"
    values:
      layout: "cases"
      permalink: /cases/:year/:month/:title.html
  -
    scope:
      path: "topics"
      type: "posts"
    values:
      layout: "topics"
      permalink: /topics/:year/:month/:title.html

# Gemfileで追加した拡張機能
gems:
  - octopress-debugger
  - octopress-hooks
  - octopress-paginate

# Build settings
markdown: kramdown

